# Generated by Django 2.1.5 on 2019-03-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=50, verbose_name='Краткое описание')),
                ('descriptions', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Полное описание')),
                ('due_date', models.DateTimeField(verbose_name='Срок выполнения')),
                ('status', models.CharField(choices=[('очередь', 'очередь'), ('в работе', 'в работе'), ('сделано', 'сделано')], default='очередь', max_length=10, verbose_name='Статус')),
                ('time_planned', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Планируемое время')),
            ],
        ),
    ]
