# Generated by Django 2.1.5 on 2019-03-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriptions',
            new_name='description',
        ),
    ]
